import type { Metadata } from "next";
import { Providers } from "./providers";
import Font from "@/app/Font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Providers>
            <Font />
            <div style={{padding: "10px"}}>
                {children}
            </div>
        </Providers>
      </body>
    </html>
  );
}
